pull_request_rules:
  - name: automatic merge for develop raised by dependabot with label dependencies
    conditions:
      - base=develop
      - label=dependencies
    actions:
      merge:
        method: merge