name: 'Webhook Action'
description: 'Send a webhook event to anywhere!'
inputs:
  url:
    description: 'The url to send the webhook event to'
    required: true
  headers:
    description: 'Additional headers to send alongside the defaults'
    required: false
  body:
    description: 'The data sent to the webhook'
    required: false
outputs:
  status: 
    description: 'The status of the webhook event'
runs:
  using: 'node12'
  main: 'dist/main.js'